language: node_js
node_js:
  - node
cache: yarn
before_script:
  - export TZ=Asia/Tokyo
script:
  - yarn test
  - yarn flow check
after_success:
  - yarn flow-coverage-report
  - yarn deploy-storybook --ci
