language: node_js
node_js:
  - node
cache: yarn
addons:
  apt:
    packages:
      - language-pack-ja
env:
  - TZ=Asia/Tokyo LANGUAGE=ja
before_script:
  - locale
script:
  - yarn test
  - yarn flow check
after_success:
  - yarn flow-coverage-report
  - yarn deploy-storybook --ci
