project_identifier_env: "CROWDIN_PROJECT_ID"
api_key_env: "CROWDIN_API_KEY"
base_path : "./"
preserve_hierarchy: true

files:
  -
    source: 'src/i18n/*/en.json'
    translation: '%original_path%/%two_letters_code%.json'
