export const SET_DAY = 'SET_DAY'
export const GET_PLAYER_ROLE = 'GET_PLAYER_ROLE'
export const SET_ROLE = 'SET_ROLE'
export const TOGGLE_OBFUCATOR = 'TOGGLE_OBFUCATOR'
export const WAIT = 'WAIT'
export const READY = 'READY'
export const POST_CHAT = 'POST_CHAT'
export const SET_IS_SENDABLE = 'SET_IS_SENDABLE'
export const CHANGE_PREDICTION_BOARD = 'CHANGE_PREDICTION_BOARD'
export const SELECT_OPTION = 'SELECT_OPTION'
export const SELECT_NO = 'SELECT_NO'
export const SELECT_YES = 'SELECT_YES'

export const SOCKET_OPEN = 'SOCKET:OPEN'
export const SOCKET_CLOSE = 'SOCKET:CLOSE'
export const SOCKET_MESSAGE = 'SOCKET:MESSAGE'
export const SOCKET_ERROR = 'SOCKET:ERROR'
export const SOCKET_SEND = 'SOCKET:SEND'
