version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    branches:
      ignore:
        gh-pages
    docker:
      - image: circleci/node:11-browsers
        environment:
          TZ: Asia/Tokyo
          LC_ALL: ja_JP.UTF-8
          LANG: ja_JP.UTF-8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:ci
      - codecov/upload:
          file: coverage
      - run: yarn test:integration
      - store_artifacts:
          path: integration/landing/__image_snapshots__
          destination: landing
      - store_artifacts:
          path: integration/lobby/__image_snapshots__
          destination: lobby
      - store_artifacts:
          path: integration/village/__image_snapshots__
          destination: village
