version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            mkdir -p ../public/stylesheets
            mkdir -p ../public/javascripts
            mkdir -p ../app/views
            yarn build:development
            yarn build:production

  unit-test:
    docker:
      - image: circleci/node:12-browsers
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:ci
      - run: yarn coverage

  visual-test:
    docker:
      - image: circleci/node:12-browsers
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:integration
      - store_artifacts:
          path: integration/landing/__image_snapshots__
          destination: landing
      - store_artifacts:
          path: integration/lobby/__image_snapshots__
          destination: lobby
      - store_artifacts:
          path: integration/village/__image_snapshots__
          destination: village

  deploy-storybook:
    docker:
      - image: circleci/node:12-browsers
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn deploy-storybook --ci

  eslint:
    docker:
      - image: circleci/node:12-browsers
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn eslint

  stylelint:
    docker:
      - image: circleci/node:12-browsers
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn stylelint

workflows:
  version: 2
  test_accept_deploy:
    jobs:
      - build
      - unit-test
      # - visual-test
      - deploy-storybook:
          requires:
            - build
            - unit-test
            # - visual-test
  lint:
    jobs:
      - eslint
      - stylelint
