export {IndexedDB} from './indexedDB'
export {Navigation} from './navigation'
export {Scope} from './scope'
export {Socket} from './socket'

export const ACTIVATE_NEXT_BUTTON = 'ACTIVATE_NEXT_BUTTON'
export const CHANGE_PREDICTION_BOARD = 'CHANGE_PREDICTION_BOARD'
export const CHANGE_DAY = 'CHANGE_DAY'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_PHASE = 'CHANGE_PHASE'
export const CLICK_HIDE_BUTTON = 'CLICK_HIDE_BUTTON'
export const DEACTIVATE_NEXT_BUTTON = 'DEACTIVATE_NEXT_BUTTON'
export const GET_PLAYER_ROLE = 'GET_PLAYER_ROLE'
export const HIDE_PREDICTION_SPEC = 'HIDE_PREDICTION_SPEC'
export const HIDE_RESULT = 'HIDE_RESULT'
export const PLAYED = 'PLAYED'
export const PROLOGUE = 'PROLOGUE'
export const POST_CHAT = 'POST_CHAT'
export const READY = 'READY'
export const RETURN_TO_LOBBY = 'RETURN_TO_LOBBY'
export const SELECT_NO = 'SELECT_NO'
export const SELECT_OPTION = 'SELECT_OPTION'
export const SELECT_YES = 'SELECT_YES'
export const SET_DAY = 'SET_DAY'
export const SET_ROLE = 'SET_ROLE'
export const SHOW_LOBBY = 'SHOW_LOBBY'
export const SHOW_PREDICTION_SPEC = 'SHOW_PREDICTION_SPEC'
export const SHOW_RESULT = 'SHOW_RESULT'
export const STAR = 'STAR'
export const TICK = 'TICK'
