export const enum BuildVillage {
  BUILD = 'buildVillage/BUILD',
  CHANGE_AVATAR = 'buildVillage/CHANGE_AVATAR',
  CHANGE_COMMENT = 'buildVillage/CHANGE_COMMENT',
  CHANGE_HOST_NAME = 'buildVillage/CHANGE_HOST_NAME',
  CHANGE_MEMBER = 'buildVillage/CHANGE_MEMBER',
  CHANGE_NUMBER_OF_PLAYERS = 'buildVillage/CHANGE_NUMBER_OF_PLAYERS',
  CHANGE_NUMBER_OF_ROBOTS = 'buildVillage/CHANGE_NUMBER_OF_ROBOTS',
  CHANGE_VILLAGE_NAME = 'buildVillage/CHANGE_VILLAGE_NAME'
}
