export const enum Message {
  AUTHORIZATION_REQUEST = 'message/AUTHORIZATION_REQUEST',
  AUTHORIZATION_REQUEST_ACCEPTED_RESPONSE = 'message/AUTHORIZATION_REQUEST_ACCEPTED_RESPONSE',
  AVATAR = 'message/AVATAR',
  HUMAN_PLAYER_SELECTION_PAGE = 'message/HUMAN_PLAYER_SELECTION_PAGE',
  LOBBY = 'message/LOBBY',
  ONYMOUS_AUDIENCE_SELECTION_PAGE = 'message/ONYMOUS_AUDIENCE_SELECTION_PAGE',
  PING = 'message/PING',
  PLAYED = 'message/PLAYED',
  ROBOT_PLAYER_SELECTION_PAGE = 'message/ROBOT_PLAYER_SELECTION_PAGE',
  SEARCH_RESULT = 'message/SEARCH_RESULT',
  SETTINGS = 'message/SETTINGS',
  WAITING_PAGE = 'message/WAITING_PAGE'
}
