export const enum SelectRobotAvatar {
  AUTHORIZATION_REQUEST_ACCEPTED = 'selectRobotAvatar/AUTHORIZATION_REQUEST_ACCEPTED',
  CHANGE_AVATAR_IMAGE = 'selectRobotAvatar/CHANGE_AVATAR_IMAGE',
  CHANGE_AVATAR_LANGUAGE = 'selectRobotAvatar/CHANGE_AVATAR_LANGUAGE',
  CHANGE_AVATAR_NAME = 'selectRobotAvatar/CHANGE_AVATAR_NAME',
  CHANGE_CHECKBOX = 'selectRobotAvatar/CHANGE_CHECKBOX',
  CREATE = 'selectRobotAvatar/CREATE',
  DELETE = 'selectRobotAvatar/DELETE',
  HOVER_AVATAR = 'selectRobotAvatar/HOVER_AVATAR',
  RUN_IN_THE_BACKGROUND = 'selectRobotAvatar/RUN_IN_THE_BACKGROUND',
  RUN_IN_THE_FOREGROUND = 'selectRobotAvatar/RUN_IN_THE_FOREGROUND',
  RENEW_AVATAR_TOKEN = 'selectRobotAvatar/RENEW_AVATAR_TOKEN',
  STOP = 'selectRobotAvatar/STOP'
}
