import {App} from './app'

export const enum Target {
  ADVANCED_SEARCH = App.ADVANCED_SEARCH,
  BUILD_VILLAGE = App.BUILD_VILLAGE,
  ID_SEARCH = App.ID_SEARCH,
  LEAVE_WAITING_PAGE = App.LEAVE_WAITING_PAGE,
  PLAY_GAME = App.PLAY_GAME,
  REFRESH = App.REFRESH,
  SHOW_ADVANCED_SEARCH = App.SHOW_ADVANCED_SEARCH,
  SHOW_BUILD_VILLAGE = App.SHOW_BUILD_VILLAGE,
  SHOW_CREDITS = App.SHOW_CREDITS,
  SHOW_CONNECTING_TO_ROBOT_PLAYER = App.SHOW_CONNECTING_TO_ROBOT_PLAYER,
  SHOW_HISTORY = App.SHOW_HISTORY,
  SHOW_HOW_TO_PLAY = App.SHOW_HOW_TO_PLAY,
  SHOW_ID_SEARCH = App.SHOW_ID_SEARCH,
  SHOW_LOBBY_FOR_AUDIENCE = App.SHOW_LOBBY_FOR_AUDIENCE,
  SHOW_LOBBY_FOR_HUMAN_PLAYER = App.SHOW_LOBBY_FOR_HUMAN_PLAYER,
  SHOW_LOBBY_FOR_ROBOT_PLAYER = App.SHOW_LOBBY_FOR_ROBOT_PLAYER,
  SHOW_MAIN = App.SHOW_MAIN,
  SHOW_SETTINGS = App.SHOW_SETTINGS
}
